DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS permissao CASCADE;
drop table if exists refresh_token cascade;


CREATE TABLE usuario (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         nome VARCHAR(100) NOT NULL,
                         email VARCHAR(100) NOT NULL,
                         cpf VARCHAR(11) NOT NULL,
                         senha VARCHAR(100) NOT NULL,
                         ativo BOOLEAN NOT NULL,
                         data_nascimento DATE NOT NULL,
                         data_ultimo_acesso TIMESTAMP,
                         criado_em TIMESTAMP NOT NULL,
                         editado_em TIMESTAMP NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_cpf UNIQUE (cpf);

CREATE TABLE permissao (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           nome VARCHAR(100) NOT NULL,
                           usuario_id BIGINT NOT NULL
);

ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (nome, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

CREATE TABLE refresh_token (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               token VARCHAR(255) NOT NULL,
                               expiracao TIMESTAMP NOT NULL,
                               usuario_id BIGINT NOT NULL
);

ALTER TABLE refresh_token ADD CONSTRAINT pk_refresh_token PRIMARY KEY (id);
ALTER TABLE refresh_token ADD CONSTRAINT uk_refresh_token_token UNIQUE (token);
ALTER TABLE refresh_token ADD CONSTRAINT uk_refresh_token_usuario UNIQUE (usuario_id); -- Um token por usuário (opcional, dependendo da sua regra)
ALTER TABLE refresh_token ADD CONSTRAINT fk_refresh_token_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id);

CREATE INDEX idx_refresh_token_valor ON refresh_token (token);